In [1]:
# You make have noticed using the vanilla CSV Reader has some limitations
# So we're going to use a powerful Python library called Pandas
import pandas as pd  # in the Python community, pd is the agreed shorthand for pandas
# this will help us make graphs
import matplotlib.pyplot as plt
%matplotlib inline

Matplotlib is building the font cache; this may take a moment.

In [3]:
# read the csv file
path = 'data/pokemon_data.csv'
# in python 1 or more rows is called a Dataframe
# pandas naming conventions (ie best practices) have all DataFrame variables end in _df
pokemon_df = pd.read_csv(path)    # Fun Fact: the plural form of Pokemon is Pokemon

In [4]:
# we can look at just the headers
pokemon_df.columns

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

In [5]:
# base_happiness is a STRING, not a variable so it needs quotes!
# bracket notation
pokemon_df['base_happiness']

0      70
1      70
2      70
3      70
4      70
       ..
796     0
797     0
798     0
799     0
800     0
Name: base_happiness, Length: 801, dtype: int64

In [6]:
# if a column has no spaces, you can use dot notation
pokemon_df.capture_rate

0       45
1       45
2       45
3       45
4       45
      ...
796     25
797    255
798     15
799      3
800      3
Name: capture_rate, Length: 801, dtype: object

In [7]:
display(pokemon_df)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [8]:
# let's look at the first five rows
pokemon_df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [9]:
# we can use indexing with DataFrames
pokemon_df[12:19]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
12,"['Shield Dust', 'Run Away']",0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,13,20,20,50,bug,poison,3.2,1,0
13,['Shed Skin'],0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,14,25,25,35,bug,poison,10.0,1,0
14,"['Swarm', 'Sniper']",0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,15,15,80,145,bug,poison,29.5,1,0
15,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.00,1.0,1.0,0.0,...,50.0,16,35,35,56,normal,flying,1.8,1,0
16,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.00,1.0,1.0,0.0,...,50.0,17,50,50,71,normal,flying,30.0,1,0
17,"['Keen Eye', 'Tangled Feet', 'Big Pecks']",0.5,1.0,1.0,2.0,1.0,1.00,1.0,1.0,0.0,...,50.0,18,135,80,121,normal,flying,39.5,1,0
18,"['Run Away', 'Guts', 'Hustle', 'Gluttony', 'Hu...",1.0,1.0,1.0,1.0,1.0,2.00,1.0,1.0,0.0,...,50.0,19,25,35,72,normal,dark,NaN,1,0

In [10]:
# A single column in pandas is referred to as a Series
pokemon_df.type1

0        grass
1        grass
2        grass
3         fire
4         fire
        ...
796      steel
797      grass
798       dark
799    psychic
800      steel
Name: type1, Length: 801, dtype: object

In [11]:
# we can also use indexing on a Series
pokemon_df.type1[0]

'grass'

In [12]:
# we can modify data in a DataFrame
pokemon_df.type1 = pokemon_df.type1.str.capitalize()
# now all type1 values will start with a upper case letter
# this is extremely helpful if you are trying to make all values the same type and/or 
# formatting
display(pokemon_df)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,Grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,Grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,Grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,Fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,Fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,Steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,Grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,Dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,Psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,Steel,fairy,80.5,7,1

In [13]:
# I can use the loc property to locate a row by a certain value
# for example, I could find the row for the pokemon 'Pikachu'
pokemon_df.loc[pokemon_df.name == 'Pikachu']

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
24,"['Static', 'Lightningrod']",1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,50.0,25,50,50,90,Electric,NaN,6.0,1,0

In [14]:
# i can also search for rows by index
pokemon_df.iloc[24]

abilities            ['Static', 'Lightningrod']
against_bug                                 1.0
against_dark                                1.0
against_dragon                              1.0
against_electric                            0.5
against_fairy                               1.0
against_fight                               1.0
against_fire                                1.0
against_flying                              0.5
against_ghost                               1.0
against_grass                               1.0
against_ground                              2.0
against_ice                                 1.0
against_normal                              1.0
against_poison                              1.0
against_psychic                             1.0
against_rock                                1.0
against_steel                               0.5
against_water                               1.0
attack                                       55
base_egg_steps                             2560
base_happiness                               70
base_total                                  320
capture_rate                                190
classfication                     Mouse Pokémon
defense                                      40
experience_growth                       1000000
height_m                                    0.4
hp                                           35
japanese_name                      Pikachuピカチュウ
name                                    Pikachu
percentage_male                            50.0
pokedex_number                               25
sp_attack                                    50
sp_defense                                   50
speed                                        90
type1                                  Electric
type2                                       NaN
weight_kg                                   6.0
generation                                    1
is_legendary                                  0
Name: 24, dtype: object

In [ ]:
# I can pull certain values from a row
pokemon_df.iloc[24].japanese_name

In [ ]:
# I could also use the loc property to just see the japanese name of the pokemon 'Pikachu'
# so the first parameter is my search query, the second parameter is the column value I want 
# to return
pokemon_df.loc[pokemon_df.name == 'Pikachu', 'japanese_name']

In [ ]:
# item function only works if you have 1 item in series
pokemon_df.loc[pokemon_df.name == 'Pikachu', 'japanese_name'].item()

In [ ]:
# the loc function returns all rows that match the condition
# this allows me to get all grass type pokemon
# remember I capitalized the type1 values, so I need to say 'Grass', not 'grass'
pokemon_df.loc[pokemon_df.type1 == 'Grass', 'name']

In [ ]:
# Analyze data with Pandas
# For example, I can see the highest and lowest values for HP
print(pokemon_df.hp.max())
print(pokemon_df.hp.min())

In [ ]:
# let's find out who these pokemon are!
# we're going to use the loc property to locate any pokemon where HP equals 255 or 1!
strong_pokemon = pokemon_df.loc[pokemon_df.hp == 255, 'name'].item()
weak_pokemon = pokemon_df.loc[pokemon_df.hp == 1, 'name'].item()
print(strong_pokemon)
print(weak_pokemon)

In [ ]:
# let's make a DataFrame of the strongest pokemon
strongest_pokemon_df = pokemon_df[pokemon_df.hp>125]
strongest_pokemon_df

In [ ]:
# I can look at their names
strongest_pokemon_df.name

In [ ]:
# let's see how many unique types there are among these pokemon
print(strongest_pokemon.type1.unique())

In [ ]:
# If bins is an integer, it defines the number of equal-width bins in the range.
plt.hist(pokemon_df.hp, bins=25)
plt.xlabel('HP')
plt.ylabel('Number of Pokemon')
plt.title('Distribution of HP amongst Pokemon')
plt.axvline(pokemon_df.hp.mean(), color='yellow', linestyle='dashed', linewidth=2)    # draw where the average is in yellow
plt.axvline(pokemon_df.hp.median(), color='red', linestyle='dashed', linewidth=2)  # draw where the median is in red

In [ ]:
# let's group our pokemon by type and see the differenes in HP
# so we are going to split our pokemon DataFrame by 'type1' using the groupby() function 
# then we'll calculate the median HP for each type
type_groupings = pokemon_df.groupby('type1')
type_groupings.hp.median()

In [ ]:
# we can also see a deeper analysis of these numbers by using describe()
# 68% Rule: In a bell-shaped normal distribution, approximately 68.3% of all data points fall 
# within one standard deviation above or below the mean.
# A score that sits exactly one standard deviation above the mean is at the 84th percentile, 
# while a score one standard deviation below the mean is at the 16th percentile.
# https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ5zQmpvtohc_KZnrOjrVPcd9q_CVs6RWB8MY-Lw7VCc_Rgqxee
type_groupings.hp.describe()

In [ ]:
# let's graph water vs fire

# make a dataframe of just water pokemon
water_df = type_groupings.get_group('Water')
# make a dataframe of just fire pokemon
fire_df = type_groupings.get_group('Fire')
plt.hist(water_df.hp, bins=20, label='Water')
plt.hist(fire_df.hp, bins=20, label='Fire')
plt.legend()
plt.title("Distribution of HP by type")
plt.xlabel("HP")
plt.ylabel("Number of Pokemon")

In [ ]:
# find the numerical correlation between two colums
# meaning: how does speed correlate to a pokemon's hp?
correlation = pokemon_df.speed.corr(pokemon_df.hp)

print(correlation) # answer: not very (1 is the strongest positive correlation, -1 strongest neg coor, 0 is no correlation)

In [1]:
pokemon_df.weight_kg.corr(pokemon_df.hp)

NameError: name 'pokemon_df' is not defined

In [ ]:
pokemon_df.height_m.corr(pokemon_df.hp)

In [ ]:
pokemon_df.base_happiness.corr(pokemon_df.hp)

In [ ]:
pokemon_values = pokemon_df[['speed', 'hp', 'sp_attack', 'sp_defense']]
corr_pokemon = pokemon_values.corr()
corr_pokemon

In [15]:
plt.matshow(pokemon_values.corr())
plt.xticks(range(pokemon_values.select_dtypes(['number']).shape[1]), pokemon_values.select_dtypes(['number']).columns, fontsize=14, rotation=45)
plt.yticks(range(pokemon_values.select_dtypes(['number']).shape[1]), pokemon_values.select_dtypes(['number']).columns, fontsize=14)
cb = plt.colorbar()
cb.ax.tick_params(labelsize=14)
plt.title('Correlation Matrix', fontsize=16);
plt.show()

# we can see a stronger correlation bewteen special attack and special defense and a weaker
# correlation with hp and speed

NameError: name 'pokemon_values' is not defined